name: "GitHub Jira Sync"
on:
  #  manually triggered 
  workflow_dispatch:

jobs:
  github_to_jira:
    runs-on: ubuntu-latest
    steps:
      - name: Sync alerts to Jira issues
        uses: github/ghas-jira-integration@v1
        with:
          jira_url: 'https://miguelarroyo.atlassian.net'
          jira_user: '${{ secrets.JIRA_USER }}'
          jira_token: '${{ secrets.JIRA_TOKEN }}'
          jira_project: 'CSI'
          github_token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
          sync_direction: 'gh2jira'
          #### Optionals #####
          jira_labels: 'red-team,blue-team,green-team'
          #### Optionals #####
  jira_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Sync alerts to Jira issues
        uses: github/ghas-jira-integration@v1
        with:
          jira_url: 'https://miguelarroyo.atlassian.net'
          jira_user: '${{ secrets.JIRA_USER }}'
          jira_token: '${{ secrets.JIRA_TOKEN }}'
          jira_project: 'CSI'
          github_token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
          sync_direction: 'jira2gh'